### ISSUE TITLE
Dotpath parsing into objects

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/py_dataset#9]
Example in test_frame_objects in dataset_test.py

For a nested object (e.g. "nameIdentifiers": [
                {   
                    "nameIdentifier": "0000-000X-XXXX-XXXX",
                    "nameIdentifierScheme": "ORCID",
                    "schemeURI": "http://orcid.org/"
                }])
I should be able to retrieve 0000-000X-XXXX-XXXX with nameIdentifiers[0].nameIdentifier (one returned), nameIdentifiers[:].nameIdentifier (an array is returned of the .nameIdentifier field).

**Comment by rsdoiel** [comment]
Fixed, typo in test. Merged into master. Ready for next release.
